name: hospital_app
description: "A new Flutter project."

# Prevent publishing to pub.dev (private project)
publish_to: 'none'

# App version: version_name + build_number
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Main dependencies
dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  connectivity_plus: ^6.0.3

# Dev dependencies (build tools, testing)
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0       # code quality rules

  flutter_launcher_icons: ^0.13.1   # app icon generator

# Flutter settings
flutter:
  uses-material-design: true

  # Assets (images, icons, etc.)
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/splash/

# App launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: true

  # Path to your app logo (must be 1024x1024 PNG)
  image_path: "assets/logo/Cardi.png"