// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6pTjcnmglX_-nR4GCuepBuX27QSTWQUI',
    appId: '1:40133651116:web:93917d147579dca8a44d09',
    messagingSenderId: '40133651116',
    projectId: 'hospitalapp-d2023',
    authDomain: 'hospitalapp-d2023.firebaseapp.com',
    storageBucket: 'hospitalapp-d2023.firebasestorage.app',
    measurementId: 'G-39467ERVQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQBbBfiKyAG0fmKpUqSBTCu0k2kSkGOg8',
    appId: '1:40133651116:android:4068d2ac66b78e89a44d09',
    messagingSenderId: '40133651116',
    projectId: 'hospitalapp-d2023',
    storageBucket: 'hospitalapp-d2023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVdAYcnKV_g9GwVQYvYEE0fRnpdl_hR7A',
    appId: '1:40133651116:ios:b68c0d85586f14f9a44d09',
    messagingSenderId: '40133651116',
    projectId: 'hospitalapp-d2023',
    storageBucket: 'hospitalapp-d2023.firebasestorage.app',
    iosBundleId: 'com.example.hospitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVdAYcnKV_g9GwVQYvYEE0fRnpdl_hR7A',
    appId: '1:40133651116:ios:b68c0d85586f14f9a44d09',
    messagingSenderId: '40133651116',
    projectId: 'hospitalapp-d2023',
    storageBucket: 'hospitalapp-d2023.firebasestorage.app',
    iosBundleId: 'com.example.hospitalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6pTjcnmglX_-nR4GCuepBuX27QSTWQUI',
    appId: '1:40133651116:web:87623a1d05eb37c6a44d09',
    messagingSenderId: '40133651116',
    projectId: 'hospitalapp-d2023',
    authDomain: 'hospitalapp-d2023.firebaseapp.com',
    storageBucket: 'hospitalapp-d2023.firebasestorage.app',
    measurementId: 'G-EP41XEJYDD',
  );

}